export default class Constant {
  // 登录标题大小
  static readonly LOGIN_SIZE: number = 30
  // 登录小标题大小
  static readonly LOGIN_LITTLE_SIZE: number = 17
  // 输入框长度
  static readonly INPUT_WIDTH: number = 300
  // 输入框高度
  static readonly INPUT_HEIGHT: number = 60
  // 按钮宽度
  static readonly BUTTON_WIDTH: number = 150
  // 按钮高度
  static readonly BUTTON_HEIGHT: number = 50
  // 登陆按钮颜色
  static readonly BUTTON_COLOR: string = '#007DFF'
  // 输入框中的图片大小
  static readonly INPUT_IMAGE_SIZE: number = 30;
  // 头像大小
  static readonly AVATAR_SIZE: number = 100;
}