################################
# Amlogic codec memory manager #
################################

####################################
# The order of directories matter. #
# Do not change.                   #
####################################

codec_mm_t-objs = codec_mm.o \
	codec_mm_scatter.o \
	codec_mm_keeper.o \
	secmem.o \
	configs/configs.o configs/configs_module.o \
	configs/configs_test.o

obj-m = codec_mm_t.o
	
